name: sejoga2025_certo
description: Aplicativo de navegação indoor para pessoas com deficiência visual.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_tts: ^4.0.2
  flutter_blue_plus: ^1.40.5
  permission_handler: ^12.0.0+1
  google_generative_ai: ^0.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/beacon_map.json
    - assets/wifi_map.json
